{% set name = "plumpy" %}
{% set version = "0.18.0" %}
{% set sha256 = "297ae50660b391033e8584017925ff63bbc95de1d5bd7ff6709a47aa634c12b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - frozendict ~=1.2
    - aio-pika ~=6.6
    - aiocontextvars ~=0.2.2  # [py < 37]
    - pyyaml ~=5.1.2
    - nest-asyncio ~=1.4.0
    - kiwipy[rmq] ~=0.7.1

test:
  imports:
    - plumpy
  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: MIT
  license_file: LICENSE
  summary: A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks.
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
    - unkcpz
