{% set name = "plumpy" %}
{% set version = "0.23.0" %}
{% set sha256 = "ec3cf7d16edcb377eba89f1a6aca9eeed534d5d639eaa5d6e40772d50872b5c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.4,<4
  run:
    - python >={{ python_min }}
    - pyyaml ~=6.0
    - nest-asyncio ~=1.5,>=1.5.1
    - kiwipy[rmq] ~=0.8.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - plumpy
    - plumpy.base

about:
  home: https://github.com/aiidateam/plumpy
  license: MIT AND GPLv3
  license_file: LICENSE.txt
  summary: A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks.
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - khsrali
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
    - unkcpz
