{% set name = "plumpy" %}
{% set version = "0.16.1" %}
{% set sha256 = "1a950bf54e9af8a552f442c650f6b1e0ab6147265d0321bd98c754964d6c6889" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - frozendict ~=1.2
    - pyyaml ~=5.1.2
    - nest-asyncio ~=1.4.0
    - aio-pika ~=6.6.1
    - aiocontextvars ~=0.2.2
    - kiwipy[rmq] ~=0.6.0

test:
  imports:
    - plumpy
  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: MIT
  license_file: LICENSE
  summary: A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks.
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
    - unkcpz
