{% set name = "plumpy" %}
{% set version = "0.19.0" %}
{% set sha256 = "743f5d503c0f5b4e4f3fd37ea2aa926d589adff8aa9dfcb3c83e46b5bb5ae225" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aio-pika ~=6.6
    - aiocontextvars ~=0.2.2  # [py < 37]
    - pyyaml ~=5.1.2
    - nest-asyncio ~=1.4.0
    - kiwipy[rmq] ~=0.7.4

test:
  imports:
    - plumpy
    - plumpy.base

about:
  home: https://github.com/aiidateam/plumpy
  license: MIT
  license_file: LICENSE
  summary: A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks.
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
    - unkcpz
