{% set name = "plumpy" %}
{% set version = "0.11.0" %}
{% set sha256 = "fa0371d547b9703f68bac7e0ce288884794dfc56d1bf3d07f663b3d784febbb9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not (py27 or py34 or py35 or py36)]

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python
    - frozendict
    - portalocker
    - pyyaml
    - tornado>=4.1, <5.0
    - future
    - kiwipy[rmq]>=0.3.1, <0.4.0
    - enum34  # [py < 34]
    - backports.tempfile  # [py < 32]

test:
  imports:
    - plumpy
  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: GPLv3, MIT
  license_file: LICENSE
  summary: "A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks."
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
