{% set name = "plumpy" %}
{% set version = "0.22.3" %}
{% set sha256 = "e58f45e6360f173babf04e2a4abacae9867622768ce2a126c8260db3b46372c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core >=3.4,<4
  run:
    - python >=3.8
    - pyyaml ~=6.0
    - nest-asyncio ~=1.5,>=1.5.1
    - kiwipy[rmq] ~=0.8.3

test:
  imports:
    - plumpy
    - plumpy.base

about:
  home: https://github.com/aiidateam/plumpy
  license: MIT AND GPLv3
  license_file: LICENSE.txt
  summary: A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks.
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - khsrali
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
    - unkcpz
