{% set name = "plumpy" %}
{% set version = "0.7.12" %}
{% set sha256 = "d679e97016b8037e1405e3c12bfd9208131326cc69cdf7781c99ab905961793b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not py27]

requirements:
  build:
    - setuptools
    - python

  host:
    - pip

  run:
    - python
    - frozendict
    - enum34  # [py < 34]
    - backports.tempfile  # [py < 32]

test:
  imports:
    - plumpy

  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: GPLv3, MIT
  license_file: LICENSE
  summary: "A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks."
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
