{% set name = "plumpy" %}
{% set version = "0.12.2" %}
{% set sha256 = "d7e7ef533198ab46826d88fe9dca3dfb97a3ae19ec942a3a547e5b6d7bf822aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not (py27 or py34 or py35 or py36)]

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python
    - frozendict
    - pika==1.0.0b1
    - kiwipy[rmq]>=0.4.2, <0.5.0
    - enum34  # [py < 34]
    - backports.tempfile  # [py < 32]
    - six

test:
  imports:
    - plumpy
  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: GPLv3, MIT
  license_file: LICENSE
  summary: "A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks."
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
