appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LIrz32SK8J5eXqpEfqF85qLHVXs7RSMv0Tum1QTvsaxpj2GVMDdTfOsMFGA/kWlTMeqi60uUzW6zCVcPxgZ84plhMwVsv990YBOhb9IZA4vOOsFyC0WyVFutAcBEQDChXUqkYiNxh7viREiexC6XojKcsZxZ872qQ/hFso1K2kGEN1SfHejtey7RxUgTzCFaq8TzmRTaTmvpgPP5hG9qnitX2X7WgXOZDt3aUaBZit3SmHiH93u2fbMqsRBP2+jkt5D4KoG70PL4zjvcRfdOsiBV2Ec0akYuRZ4C20Qo9AjB+sXR8uF9rGzPR5v7TLa11URZ9XlZV9q0RlhekvMoQYSS+k+Wsdgh/vBT10Mrysg6rhBHRrRAXyz7JlN/ugW5F7rxEQXBm8/duhNtcPbrDLue3iPurrAX5+L0J1HH1v5OVSvrdosWidKKNnkkJA6fq8Qlg8n8iiaSEFMRbIt2tZUtG3nwxm9x8OO7uycqcfa1y0cN/UmhhUydomHdLqojpgrZxEUb0JjLI+/BUMongoKMkvWEpE+HxPYjZ0Arg7RuedzZxNujKzRhlNciZc2D/xeZEKzTpXGJOyFiDM+sCtBv6TfEWzBpuBtK/GhG+Hs0Xgs9oKvg3yyLsG/wegk/5Eq/qeMYH6WmDVHS6zXPVxN+XOp+Ojmh8cClaEa44QU=}
conda_forge_output_validation: true
